export { default as Home } from "./Home";
export { default as Profile } from "./Profile";
export { default as EditProfile } from "./EditProfile";
export { default as Dashboard } from "./Dashboard"
export { default as DetailProduct } from "./DetailProduct";
export { default as Produk } from "./Product";
export { default as StatusPembelian } from "./StatusPembelian";
export { default as ProdukAdmin } from './ProductAdmin'
export { default as Transaksi } from './Transaksi'
export { default as User } from './User'
